### ISSUE TITLE
Use ref instead of global id

### ISSUE THREAD

**Issue by jschurse** [schlunsen/vue-audiomotion#1]
In order to decouple the component from the global DOM a ref should be used instead of an id
https://github.com/schlunsen/vue-audiomotion/blob/864a919e7ef7344e0b37c3be31b7fadc1946aa4c/src/components/AudioMotion.vue#L2

https://vuejs.org/v2/guide/components-edge-cases.html

**Comment by schlunsen** [comment]
Hi @jschurse,
Excellent point! 

Hereby updated and published to npm
